// <auto-generated />
using AddToCartAPI.Model.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddToCartAPI.Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AddToCartAPI.Model.Models.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("AddToCartAPI.Model.Models.CartProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("AddToCartAPI.Model.Models.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<long>("VariantId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            CategoryId = 1L,
                            Price = 150m,
                            ProductName = "test_product1",
                            Stock = 1000,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 2L,
                            CategoryId = 1L,
                            Price = 150m,
                            ProductName = "test_product2",
                            Stock = 1000,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 3L,
                            CategoryId = 1L,
                            Price = 150m,
                            ProductName = "test_product3",
                            Stock = 1000,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 4L,
                            CategoryId = 2L,
                            Price = 350m,
                            ProductName = "test_product4",
                            Stock = 500,
                            VariantId = 3L
                        },
                        new
                        {
                            ProductId = 5L,
                            CategoryId = 3L,
                            Price = 50m,
                            ProductName = "test_product5",
                            Stock = 750,
                            VariantId = 4L
                        },
                        new
                        {
                            ProductId = 6L,
                            CategoryId = 2L,
                            Price = 120m,
                            ProductName = "test_product6",
                            Stock = 250,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 7L,
                            CategoryId = 3L,
                            Price = 290m,
                            ProductName = "test_product7",
                            Stock = 250,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 8L,
                            CategoryId = 4L,
                            Price = 40m,
                            ProductName = "test_product8",
                            Stock = 250,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 9L,
                            CategoryId = 1L,
                            Price = 10m,
                            ProductName = "test_product9",
                            Stock = 250,
                            VariantId = 1L
                        },
                        new
                        {
                            ProductId = 10L,
                            CategoryId = 1L,
                            Price = 30m,
                            ProductName = "test_product10",
                            Stock = 250,
                            VariantId = 1L
                        });
                });

            modelBuilder.Entity("AddToCartAPI.Model.Models.CartProduct", b =>
                {
                    b.HasOne("AddToCartAPI.Model.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AddToCartAPI.Model.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AddToCartAPI.Model.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
